[project]
name = "conduit-shared"
dynamic = ["version"]
description = "Shared models for Conduit packages"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.10.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/shared"]

[tool.hatch.version]
path = "src/shared/_version.py"
