[project]
name = "conduit-py"
version = "0.0.1"
description = "Background jobs and APIs for Python. Like Modal, but self-hostable."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.0",
    "croniter>=6.0.0",
    "fastapi>=0.115.0",
    "pydantic>=2.10.0",
    "pydantic-settings>=2.12.0",
    "redis>=5.2.0",
    "rich>=13.9.0",
    "conduit-server",
    "conduit-shared",
    "typer>=0.15.0",
    "uvicorn>=0.34.0",
]

[project.scripts]
conduit = "conduit.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/conduit"]

[tool.uv.sources]
"conduit-server" = { workspace = true }
"conduit-shared" = { workspace = true }
